---
platform: linux-amd64
group: exporters
user: exporters
tmp_path: /tmp
binary_path: /etc/exporters

#####################
### node_exporter ###
#####################
node_exporter_enable: true
node_exporter_version: v0.18.1
node_exporter_path: "{{ binary_path }}/node_exporter"
# Pls. read more at <https://github.com/prometheus/node_exporter#enabled-by-default>
sha256sum_node_exporter:
node_options: [] 
  # - devstat
  # - interrupts
  # - mountstats
  # - ntp
node_exporter_default_value_path: /etc/default/

##########################
### memcached_exporter ###
##########################
memcached_exporter_enable: true
memcached_exporter_version: 
memcached_exporter_path: "{{ binary_path }}/memcached_exporter"
memcached_exporter_options: []
memcached_exporter_default_value_path: /etc/default/
sha256sum_memcached_exporter:

########################
### haproxy_exporter ###
########################
haproxy_exporter_enable: true
haproxy_exporter_version: 
haproxy_exporter_path: "{{ binary_path }}/haproxy_exporter"
haproxy_exporter_options: [] #read options flags in haproxy_exporter_option_flags.j2 (in templates)
haproxy_exporter_default_value_path: /etc/default/
sha256sum_haproxy_exporter:

#######################
### statsd_exporter ###
#######################
statsd_exporter_enable: true
statsd_exporter_version: 
statsd_exporter_path: "{{ binary_path }}/statsd_exporter"
statsd_exporter_options: [] #read option flags at https://github.com/prometheus/statsd_exporter
statsd_exporter_default_value_path: /etc/default/
sha256sum_statsd_exporter:

#########################
### blackbox_exporter ###
#########################
blackbox_exporter_enable: true
blackbox_exporter_version: 
blackbox_exporter_path: "{{ binary_path }}/blackbox_exporter"
blackbox_exporter_options: [] #read option flags at https://github.com/prometheus/blackbox_exporter
blackbox_exporter_default_value_path: /etc/default/
sha256sum_blackbox_exporter:

#####################
### snmp_exporter ###
#####################
snmp_exporter_enable: true
snmp_exporter_version: 
snmp_exporter_path: "{{ binary_path }}/snmp_exporter"
snmp_exporter_options: [] #read option flags at https://github.com/prometheus/snmp_exporter
smnp_exporter_default_value_path: /etc/default/
sha256sum_snmp_exporter:

#########################
### influxdb_exporter ###
#########################
influxdb_exporter_enable: true
influxdb_exporter_version: 
influxdb_exporter_path: "{{ binary_path }}/influxdb_exporter"
sha256sum_influxdb_exporter:

#########################
### collectd_exporter ###
#########################
collectd_exporter_enable: true
collectd_exporter_version: 
collectd_exporter_path: "{{ binary_path }}/collectd_exporter"
sha256sum_collectd_exporter:

#######################
### consul_exporter ###
#######################
consul_exporter_enable: true
consul_exporter_version: 
consul_exporter_path: "{{ binary_path }}/consul_exporter"
consul_exporter_options: #read option flags at https://github.com/prometheus/consul_exporter
sha256sum_consul_exporter:

#########################
### graphite_exporter ###
#########################
graphite_exporter_enable: true
graphite_exporter_version: 
graphite_exporter_path: "{{ binary_path }}/graphite_exporter"
graphite_exporter_options: #read option flags at https://github.com/prometheus/graphite_exporter
graphite_exporter_default_value_path: /etc/default/
sha256sum_graphite_exporter:

#######################
### mysqld_exporter ###
#######################
mysqld_exporter_enable: true
mysqld_exporter_version: 
mysqld_exporter_path: "{{ binary_path }}/mysqld_exporter"
mysqld_exporter_options: #read option flags at https://github.com/prometheus/graphite_exporter
sha256sum_mysqld_exporter:

###########################
### cloudwatch_exporter ###
###########################
cloudwatch_exporter_enable: true
cloudwatch_exporter_version: 
cloudwatch_exporter_path: "{{ binary_path }}/cloudwatch_exporter"
cloudwatch_exporter_default_value_path:

####################
### jmx_exporter ###
####################
jmx_exporter_enable: true
jmx_exporter_version: 
jmx_exporter_path: "{{ binary_path }}/jmx_exporter"
jmx_exporter_default_value_path: