---
- name: download blackbox_exporter packages
  get_url:
    url: "https://github.com/prometheus/blackbox_exporter/releases/download/{{ blackbox_exporter_version }}/blackbox_exporter-{{blackbox_exporter_version[1:]}}.{{platform}}.tar.gz"
    dest: "{{ tmp_path }}/blackbox_exporter.tar.gz"
    mode: 0766
    sha256sum: "{{ sha256sum_blackbox_exporter }}"

- name: Creates directory blackbox_exporter
  file:
    path: "{{ blackbox_exporter_path }}"
    state: directory

- name: Extract file
  unarchive:
    src: "{{ tmp_path }}/blackbox_exporter.tar.gz"
    dest: "{{ blackbox_exporter_path }}"
    remote_src: yes
    mode: 0766
    owner: "{{user}}"
    group: "{{group}}"
    extra_opts: [--strip-components=1]

- name: Clean tar file
  file:
    path: "{{ tmp_path }}/blackbox_exporter.tar.gz"
    state: absent

- name: Create config file
  template:
    src: ./templates/blackbox_exporter_config_file.yml.j2
    dest: "{{ blackbox_exporter_default_value_path }}/blackbox_exporter_config_file.yml"
    mode: '0644'

- name: Create service file
  template:
    src: ./templates/blackbox_exporter.service.j2
    dest: /etc/systemd/system/blackbox_exporter.service
    mode: '0644'
  notify:
    - Ensure blackbox_exporter is running
    - Restart blackbox_exporter