---
- name: download collectd_exporter packages
  get_url:
    url: "https://github.com/prometheus/collectd_exporter/releases/download/{{ collectd_exporter_version }}/collectd_exporter-{{collectd_exporter_version[1:]}}.{{platform}}.tar.gz"
    dest: "{{ tmp_path }}/collectd_exporter.tar.gz"
    mode: 0766
    sha256sum: "{{ sha256sum_collectd_exporter }}"

- name: Creates directory collectd_exporter
  file:
    path: "{{ collectd_exporter_path }}"
    state: directory

- name: Extract file
  unarchive:
    src: "{{ tmp_path }}/collectd_exporter.tar.gz"
    dest: "{{ collectd_exporter_path }}"
    remote_src: yes
    mode: 0766
    owner: "{{ user }}"
    group: "{{ group }}"
    extra_opts: [--strip-components=1]

- name: Clean tar file
  file:
    path: "{{ tmp_path }}/collectd_exporter.tar.gz"
    state: absent
    
- name: Create service file
  template:
    src: ./templates/collectd_exporter.service.j2
    dest: /etc/systemd/system/collectd_exporter.service
    mode: '0644'
  notify:
    - Ensure collectd_exporter is running
    - Restart collectd_exporter