---
- name: download consul_exporter packages
  get_url:
    url: "https://github.com/prometheus/consul_exporter/releases/download/{{ consul_exporter_version }}/consul_exporter-{{ consul_exporter_version[1:]}}.{{platform}}.tar.gz"
    dest: "{{ tmp_path }}/consul_exporter.tar.gz"
    mode: 0766
    sha256sum: "{{ sha256sum_consul_exporter }}"

- name: Creates directory consul_exporter
  file:
    path: "{{ consul_exporter_path }}"
    state: directory

- name: Extract file
  unarchive:
    src: "{{ tmp_path }}/consul_exporter.tar.gz"
    dest: "{{ consul_exporter_path }}"
    remote_src: yes
    mode: 0766
    owner: "{{user}}"
    group: "{{group}}"
    extra_opts: [--strip-components=1]

- name: Clean tar file
  file:
    path: "{{ tmp_path }}/consul_exporter.tar.gz"
    state: absent

- name: Create service file
  template:
    src: ./templates/consul_exporter.service.j2
    dest: /etc/systemd/system/consul_exporter.service
    mode: '0644'
  notify:
    - Ensure consul_exporter is running
    - Restart consul_exporter