---
- name: download graphite_exporter packages
  get_url:
    url: "https://github.com/prometheus/graphite_exporter/releases/download/{{ graphite_exporter_version }}/graphite_exporter-{{graphite_exporter_version[1:]}}.{{platform}}.tar.gz"
    dest: "{{ tmp_path }}/graphite_exporter.tar.gz"
    mode: 0766
    sha256sum: "{{ sha256sum_graphite_exporter }}"

- name: Creates directory graphite_exporter
  file:
    path: "{{ graphite_exporter_path }}"
    state: directory

- name: Extract file
  unarchive:
    src: "{{ tmp_path }}/graphite_exporter.tar.gz"
    dest: "{{ graphite_exporter_path }}"
    remote_src: yes
    mode: 0766
    owner: "{{user}}"
    group: "{{group}}"
    extra_opts: [--strip-components=1]

- name: Clean tar file
  file:
    path: "{{ tmp_path }}/graphite_exporter.tar.gz"
    state: absent

- name: Create config file
  template:
    src: ./templates/graphite_exporter_config_file.yml.j2
    dest: "{{ graphite_exporter_default_value_path }}/graphite_exporter_config_file.yml"
    mode: '0644'

- name: Create service file
  template:
    src: ./templates/graphite_exporter.service.j2
    dest: /etc/systemd/system/graphite_exporter.service
    mode: '0644'
  notify:
    - Ensure graphite_exporter is running
    - Restart graphite_exporter