---
- include_tasks: pre_exporter.yml

- include_tasks: blackbox_exporter.yml
  when: blackbox_exporter_enable
- include_tasks: cloudwatch_exporter.yml
  when: cloudwatch_exporter_enable
- include_tasks: collectd_exporter.yml
  when: collectd_exporter_enable
- include_tasks: consul_exporter.yml
  when: consul_exporter_enable
- include_tasks: graphite_exporter.yml
  when: graphite_exporter_enable
- include_tasks: haproxy_exporter.yml
  when: haproxy_exporter_enable
- include_tasks: jmx_exporter.yml
  when: jmx_exporter_enable
- include_tasks: memcached_exporter.yml
  when: memcached_exporter_enable
- include_tasks: node_exporter.yml
  when: node_exporter_enable
- include_tasks: snmp_exporter.yml
  when: snmp_exporter_enable
- include_tasks: statsd_exporter.yml
  when: statsd_exporter_enable