---
- name: download snmp_exporter packages
  get_url:
    url: "https://github.com/prometheus/snmp_exporter/releases/download/{{ node_exporter_version }}/node_exporter-{{node_exporter_version[1:]}}.{{platform}}.tar.gz"
    dest: "{{ tmp_path }}/node_exporter.tar.gz"
    mode: 0766
    sha256sum: "{{ sha256sum_node_exporter }}"

- name: Creates directory snmp_exporter
  file:
    path: "{{ snmp_exporter_path }}"
    state: directory

- name: Extract file
  unarchive:
    src: "{{ tmp_path }}/snmp_exporter.tar.gz"
    dest: "{{ snmp_exporter_path }}"
    remote_src: yes
    mode: 0766
    owner: "{{user}}"
    group: "{{group}}"
    extra_opts: [--strip-components=1]

- name: Clean tar file
  file:
    path: "{{ tmp_path }}/snmp_exporter.tar.gz"
    state: absent

- name: Create config file
  template:
    src: ./templates/snmp_exporter_config_file.yml.j2
    dest: "{{ snmp_exporter_default_value_path }}/snmp_exporter_config_file.yml"
    mode: '0644'


- name: Create service file
  template:
    src: ./templates/snmp_exporter.service.j2
    dest: /etc/systemd/system/snmp_exporter.service
    mode: '0644'
  notify:
    - Ensure snmp_exporter is running
    - Restart snmp_exporter