---
- name: download statsd_exporter packages
  get_url:
    url: "https://github.com/prometheus/statsd_exporter/releases/download/{{ statsd_exporter_version }}/statsd_exporter-{{node_exporter_version[1:]}}.{{platform}}.tar.gz"
    dest: "{{ tmp_path }}/statsd_exporter.tar.gz"
    mode: 0766
    sha256sum: "{{ sha256sum_statsd_exporter }}"

- name: Creates directory statsd_exporter
  file:
    path: "{{ statsd_exporter_path }}"
    state: directory

- name: Extract file
  unarchive:
    src: "{{ tmp_path }}/statsd_exporter.tar.gz"
    dest: "{{ statsd_exporter_path }}"
    remote_src: yes
    mode: 0766
    owner: "{{user}}"
    group: "{{group}}"
    extra_opts: [--strip-components=1]

- name: Clean tar file
  file:
    path: "{{ tmp_path }}/statsd_exporter.tar.gz"
    state: absent

- name: Create mapping config file
  template:
    src: ./templates/stasd_exporter_mapping_configs.yml.j2
    dest: "{{ statsd_exporter_default_value_path }}/stasd_exporter_mapping_configs.yml"
    mode: '0644'

- name: Create service file
  template:
    src: ./templates/statsd_exporter.service.j2
    dest: /etc/systemd/system/statsd_exporter.service
    mode: '0644'
  notify:
    - Ensure statsd_exporter is running
    - Restart statsd_exporter