---
- name: Ensure node_exporter is running
  service:
    name: node_exporter
    state: started
  become: yes

- name: Restart node_exporter
  service:
    name: node_exporter
    state: restarted
  become: yes

- name: Ensure memcached_exporter is running
  service:
    name: memcached_exporter
    state: started
  become: yes

- name: Restart memcached_exporter
  service:
    name: memcached_exporter
    state: restarted
  become: yes

- name: Ensure haproxy_exporter is running
  service:
    name: haproxy_exporter
    state: started
  become: yes

- name: Restart haproxy_exporter
  service:
    name: haproxy_exporter
    state: restarted
  become: yes

- name: Ensure statsd_exporter is running
  service:
    name: statsd_exporter
    state: started
  become: yes

- name: Restart statsd_exporter
  service:
    name: statsd_exporter
    state: restarted
  become: yes

- name: Ensure blackbox_exporter is running
  service:
    name: blackbox_exporter
    state: started
  become: yes

- name: Restart blackbox_exporter
  service:
    name: blackbox_exporter
    state: restarted
  become: yes

- name: Ensure snmp_exporter is running
  service:
    name: snmp_exporter
    state: started
  become: yes

- name: Restart snmp_exporter
  service:
    name: snmp_exporter
    state: restarted
  become: yes

- name: Ensure influxdb_exporter is running
  service:
    name: influxdb_exporter
    state: started
  become: yes

- name: Restart influxdb_exporter
  service:
    name: influxdb_exporter
    state: restarted
  become: yes

- name: Ensure collectd_exporter is running
  service:
    name: collectd_exporter
    state: started
  become: yes

- name: Restart collectd_exporter
  service:
    name: collectd_exporter
    state: restarted
  become: yes

- name: Ensure consul_exporter is running
  service:
    name: consul_exporter
    state: started
  become: yes

- name: Restart consul_exporter
  service:
    name: consul_exporter
    state: restarted
  become: yes

- name: Ensure graphite_exporter is running
  service:
    name: graphite_exporter
    state: started
  become: yes

- name: Restart graphite_exporter
  service:
    name: graphite_exporter
    state: restarted
  become: yes

- name: Ensure mysqld_exporter is running
  service:
    name: mysqld_exporter
    state: started
  become: yes

- name: Restart mysqld_exporter
  service:
    name: mysqld_exporter
    state: restarted
  become: yes